name: Deploy to Salesforce

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global

    - name: Authenticate to Salesforce
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_LOGIN_URL: ${{ secrets.SF_LOGIN_URL }}
      run: |
        echo "Authenticating to Salesforce..."
        sfdx force:auth:password:grant --username $SF_USERNAME --password $SF_PASSWORD --instanceurl $SF_LOGIN_URL --setdefaultusername

    - name: Deploy source to Salesforce
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
      run: |
        echo "Deploying source to Salesforce..."
        sfdx force:source:deploy -p force-app/main/default --targetusername $SF_USERNAME --wait 10
