name: Deploy to Salesforce

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli

      - name: Authenticate with Salesforce using Auth URL
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > sfdx-auth.txt
          sfdx auth:sfdxurl:store -f sfdx-auth.txt -a MyOrg

      - name: Deploy metadata to Salesforce
        run: |
          sfdx force:source:deploy -p force-app/main/default -u MyOrg -w 10


