name: Deploy to Salesforce

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'force-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Authenticate to Salesforce via JWT
        env:
          SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
          SF_INSTANCE_URL: https://empathetic-narwhal-6keh3r-dev-ed.trailblaze.my.salesforce.com
        run: |
          echo "${SF_JWT_KEY}" | tr -d '\r' > server.key
          sf org login jwt \
            --username $SF_USERNAME \
            --jwt-key-file server.key \
            --client-id $SF_CONSUMER_KEY \
            --instance-url $SF_INSTANCE_URL \
            --set-default

      - name: Deploy source to Salesforce (run all local tests)
        run: |
          sf project deploy start \
            --source-dir force-app/main/default \
            --test-level RunLocalTests \
            --wait 10

